server:
  port: 8081

############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  sso-server:
    ticket-timeout: 300
    allow-url: "*"
    # 模式三
    is-http: true
  sign:
    secret-key: kQwIOrYvnXmSDkwEiFngrKidMcdrgKor
  # 模式一： 共享cookie
  cookie:
    domain: stp.com

spring:
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    password:
  mvc:
    favicon:
      enabled: false

forest:
  log-enabled: false

